@startuml
' ====== menutec ======
left to right direction
actor Cliente
actor Administrador
actor Lider 

Cliente --> (Registrarse)
Cliente --> (Iniciar sesión)
Cliente --> (Ver menu )
Cliente --> (Cerrar secion)

Administrador --> (Gestionar menu)
Administrador --> (actualizar el menu)

Cliente --> (Optinar sobre menu)
Cliente --> (Clasificar el plato )

Lider --> (Gestion de la pagina) 
Lider --> (Encargado deel matenimiento) 
@enduml
